// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Grpc_course/prime_number/primepb/prime.proto

package primepb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InputRequest struct {
	InputNumber          int32    `protobuf:"varint,1,opt,name=input_number,json=inputNumber,proto3" json:"input_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InputRequest) Reset()         { *m = InputRequest{} }
func (m *InputRequest) String() string { return proto.CompactTextString(m) }
func (*InputRequest) ProtoMessage()    {}
func (*InputRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb70402da02aea79, []int{0}
}

func (m *InputRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InputRequest.Unmarshal(m, b)
}
func (m *InputRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InputRequest.Marshal(b, m, deterministic)
}
func (m *InputRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InputRequest.Merge(m, src)
}
func (m *InputRequest) XXX_Size() int {
	return xxx_messageInfo_InputRequest.Size(m)
}
func (m *InputRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InputRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InputRequest proto.InternalMessageInfo

func (m *InputRequest) GetInputNumber() int32 {
	if m != nil {
		return m.InputNumber
	}
	return 0
}

type PrimeNumbers struct {
	OutputNumber         int32    `protobuf:"varint,1,opt,name=output_number,json=outputNumber,proto3" json:"output_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrimeNumbers) Reset()         { *m = PrimeNumbers{} }
func (m *PrimeNumbers) String() string { return proto.CompactTextString(m) }
func (*PrimeNumbers) ProtoMessage()    {}
func (*PrimeNumbers) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb70402da02aea79, []int{1}
}

func (m *PrimeNumbers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimeNumbers.Unmarshal(m, b)
}
func (m *PrimeNumbers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimeNumbers.Marshal(b, m, deterministic)
}
func (m *PrimeNumbers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimeNumbers.Merge(m, src)
}
func (m *PrimeNumbers) XXX_Size() int {
	return xxx_messageInfo_PrimeNumbers.Size(m)
}
func (m *PrimeNumbers) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimeNumbers.DiscardUnknown(m)
}

var xxx_messageInfo_PrimeNumbers proto.InternalMessageInfo

func (m *PrimeNumbers) GetOutputNumber() int32 {
	if m != nil {
		return m.OutputNumber
	}
	return 0
}

func init() {
	proto.RegisterType((*InputRequest)(nil), "prime.InputRequest")
	proto.RegisterType((*PrimeNumbers)(nil), "prime.PrimeNumbers")
}

func init() {
	proto.RegisterFile("Grpc_course/prime_number/primepb/prime.proto", fileDescriptor_bb70402da02aea79)
}

var fileDescriptor_bb70402da02aea79 = []byte{
	// 177 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x71, 0x2f, 0x2a, 0x48,
	0x8e, 0x4f, 0xce, 0x2f, 0x2d, 0x2a, 0x4e, 0xd5, 0x2f, 0x28, 0xca, 0xcc, 0x4d, 0x8d, 0xcf, 0x2b,
	0xcd, 0x4d, 0x4a, 0x2d, 0x82, 0x70, 0x0a, 0x92, 0x20, 0xb4, 0x5e, 0x41, 0x51, 0x7e, 0x49, 0xbe,
	0x10, 0x2b, 0x98, 0xa3, 0x64, 0xc8, 0xc5, 0xe3, 0x99, 0x57, 0x50, 0x5a, 0x12, 0x94, 0x5a, 0x58,
	0x9a, 0x5a, 0x5c, 0x22, 0xa4, 0xc8, 0xc5, 0x93, 0x09, 0xe2, 0x43, 0xb5, 0x4a, 0x30, 0x2a, 0x30,
	0x6a, 0xb0, 0x06, 0x71, 0x83, 0xc5, 0xfc, 0xc0, 0x42, 0x4a, 0xc6, 0x5c, 0x3c, 0x01, 0x20, 0xbd,
	0x10, 0x6e, 0xb1, 0x90, 0x32, 0x17, 0x6f, 0x7e, 0x69, 0x09, 0x86, 0x1e, 0x1e, 0x88, 0x20, 0x44,
	0x95, 0x91, 0x37, 0x54, 0x53, 0x70, 0x6a, 0x51, 0x59, 0x66, 0x72, 0xaa, 0x90, 0x35, 0x17, 0x37,
	0x98, 0xef, 0x92, 0x9a, 0x9c, 0x9f, 0x5b, 0x20, 0x24, 0xac, 0x07, 0x71, 0x1b, 0xb2, 0x5b, 0xa4,
	0x60, 0x82, 0xc8, 0xb6, 0x29, 0x31, 0x18, 0x30, 0x3a, 0x71, 0x46, 0xb1, 0x43, 0xbd, 0x94, 0xc4,
	0x06, 0xf6, 0x8d, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x90, 0xf6, 0xd1, 0x0b, 0xfd, 0x00, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PrimeServiceClient is the client API for PrimeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PrimeServiceClient interface {
	PrimeDecomp(ctx context.Context, in *InputRequest, opts ...grpc.CallOption) (PrimeService_PrimeDecompClient, error)
}

type primeServiceClient struct {
	cc *grpc.ClientConn
}

func NewPrimeServiceClient(cc *grpc.ClientConn) PrimeServiceClient {
	return &primeServiceClient{cc}
}

func (c *primeServiceClient) PrimeDecomp(ctx context.Context, in *InputRequest, opts ...grpc.CallOption) (PrimeService_PrimeDecompClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PrimeService_serviceDesc.Streams[0], "/prime.PrimeService/PrimeDecomp", opts...)
	if err != nil {
		return nil, err
	}
	x := &primeServicePrimeDecompClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PrimeService_PrimeDecompClient interface {
	Recv() (*PrimeNumbers, error)
	grpc.ClientStream
}

type primeServicePrimeDecompClient struct {
	grpc.ClientStream
}

func (x *primeServicePrimeDecompClient) Recv() (*PrimeNumbers, error) {
	m := new(PrimeNumbers)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PrimeServiceServer is the server API for PrimeService service.
type PrimeServiceServer interface {
	PrimeDecomp(*InputRequest, PrimeService_PrimeDecompServer) error
}

func RegisterPrimeServiceServer(s *grpc.Server, srv PrimeServiceServer) {
	s.RegisterService(&_PrimeService_serviceDesc, srv)
}

func _PrimeService_PrimeDecomp_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(InputRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PrimeServiceServer).PrimeDecomp(m, &primeServicePrimeDecompServer{stream})
}

type PrimeService_PrimeDecompServer interface {
	Send(*PrimeNumbers) error
	grpc.ServerStream
}

type primeServicePrimeDecompServer struct {
	grpc.ServerStream
}

func (x *primeServicePrimeDecompServer) Send(m *PrimeNumbers) error {
	return x.ServerStream.SendMsg(m)
}

var _PrimeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "prime.PrimeService",
	HandlerType: (*PrimeServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PrimeDecomp",
			Handler:       _PrimeService_PrimeDecomp_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "Grpc_course/prime_number/primepb/prime.proto",
}
