// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bidi1/basicpb/basic.proto

package basicpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BidiGreeting struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BidiGreeting) Reset()         { *m = BidiGreeting{} }
func (m *BidiGreeting) String() string { return proto.CompactTextString(m) }
func (*BidiGreeting) ProtoMessage()    {}
func (*BidiGreeting) Descriptor() ([]byte, []int) {
	return fileDescriptor_681faed5905fce7c, []int{0}
}

func (m *BidiGreeting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BidiGreeting.Unmarshal(m, b)
}
func (m *BidiGreeting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BidiGreeting.Marshal(b, m, deterministic)
}
func (m *BidiGreeting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BidiGreeting.Merge(m, src)
}
func (m *BidiGreeting) XXX_Size() int {
	return xxx_messageInfo_BidiGreeting.Size(m)
}
func (m *BidiGreeting) XXX_DiscardUnknown() {
	xxx_messageInfo_BidiGreeting.DiscardUnknown(m)
}

var xxx_messageInfo_BidiGreeting proto.InternalMessageInfo

func (m *BidiGreeting) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *BidiGreeting) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

type BidiStreamGreetRequest struct {
	Greeting             *BidiGreeting `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *BidiStreamGreetRequest) Reset()         { *m = BidiStreamGreetRequest{} }
func (m *BidiStreamGreetRequest) String() string { return proto.CompactTextString(m) }
func (*BidiStreamGreetRequest) ProtoMessage()    {}
func (*BidiStreamGreetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_681faed5905fce7c, []int{1}
}

func (m *BidiStreamGreetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BidiStreamGreetRequest.Unmarshal(m, b)
}
func (m *BidiStreamGreetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BidiStreamGreetRequest.Marshal(b, m, deterministic)
}
func (m *BidiStreamGreetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BidiStreamGreetRequest.Merge(m, src)
}
func (m *BidiStreamGreetRequest) XXX_Size() int {
	return xxx_messageInfo_BidiStreamGreetRequest.Size(m)
}
func (m *BidiStreamGreetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BidiStreamGreetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BidiStreamGreetRequest proto.InternalMessageInfo

func (m *BidiStreamGreetRequest) GetGreeting() *BidiGreeting {
	if m != nil {
		return m.Greeting
	}
	return nil
}

type BidiGreetStreamResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BidiGreetStreamResponse) Reset()         { *m = BidiGreetStreamResponse{} }
func (m *BidiGreetStreamResponse) String() string { return proto.CompactTextString(m) }
func (*BidiGreetStreamResponse) ProtoMessage()    {}
func (*BidiGreetStreamResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_681faed5905fce7c, []int{2}
}

func (m *BidiGreetStreamResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BidiGreetStreamResponse.Unmarshal(m, b)
}
func (m *BidiGreetStreamResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BidiGreetStreamResponse.Marshal(b, m, deterministic)
}
func (m *BidiGreetStreamResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BidiGreetStreamResponse.Merge(m, src)
}
func (m *BidiGreetStreamResponse) XXX_Size() int {
	return xxx_messageInfo_BidiGreetStreamResponse.Size(m)
}
func (m *BidiGreetStreamResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BidiGreetStreamResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BidiGreetStreamResponse proto.InternalMessageInfo

func (m *BidiGreetStreamResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*BidiGreeting)(nil), "basic.BidiGreeting")
	proto.RegisterType((*BidiStreamGreetRequest)(nil), "basic.BidiStreamGreetRequest")
	proto.RegisterType((*BidiGreetStreamResponse)(nil), "basic.BidiGreetStreamResponse")
}

func init() { proto.RegisterFile("bidi1/basicpb/basic.proto", fileDescriptor_681faed5905fce7c) }

var fileDescriptor_681faed5905fce7c = []byte{
	// 231 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4c, 0xca, 0x4c, 0xc9,
	0x34, 0xd4, 0x4f, 0x4a, 0x2c, 0xce, 0x4c, 0x2e, 0x48, 0x82, 0xd0, 0x7a, 0x05, 0x45, 0xf9, 0x25,
	0xf9, 0x42, 0xac, 0x60, 0x8e, 0x92, 0x17, 0x17, 0x8f, 0x53, 0x66, 0x4a, 0xa6, 0x7b, 0x51, 0x6a,
	0x6a, 0x49, 0x66, 0x5e, 0xba, 0x90, 0x2c, 0x17, 0x57, 0x5a, 0x66, 0x51, 0x71, 0x49, 0x7c, 0x5e,
	0x62, 0x6e, 0xaa, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x27, 0x58, 0xc4, 0x2f, 0x31, 0x37,
	0x55, 0x48, 0x9a, 0x8b, 0x33, 0x27, 0x11, 0x26, 0xcb, 0x04, 0x96, 0xe5, 0x00, 0x09, 0x80, 0x24,
	0x95, 0x3c, 0xb9, 0xc4, 0x40, 0x66, 0x05, 0x97, 0x14, 0xa5, 0x26, 0xe6, 0x82, 0x4d, 0x0c, 0x4a,
	0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0xd2, 0xe7, 0xe2, 0x48, 0x87, 0xda, 0x00, 0x36, 0x93, 0xdb,
	0x48, 0x58, 0x0f, 0xe2, 0x18, 0x64, 0xcb, 0x83, 0xe0, 0x8a, 0x94, 0x0c, 0xb9, 0xc4, 0xe1, 0x32,
	0x10, 0xf3, 0x82, 0x52, 0x8b, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85, 0xc4, 0xb8, 0xd8, 0x8a, 0x52,
	0x8b, 0x4b, 0x73, 0x4a, 0xa0, 0xae, 0x83, 0xf2, 0x8c, 0xb2, 0xb8, 0x04, 0x10, 0x5a, 0x52, 0x8b,
	0xca, 0x32, 0x93, 0x53, 0x85, 0xc2, 0xb8, 0xf8, 0xd1, 0x5c, 0x24, 0x24, 0x8b, 0x64, 0x31, 0xa6,
	0x4b, 0xa5, 0xe4, 0xd0, 0xdd, 0x85, 0x6a, 0xbb, 0x12, 0x83, 0x06, 0xa3, 0x01, 0xa3, 0x13, 0x67,
	0x14, 0x3b, 0x34, 0x4c, 0x93, 0xd8, 0xc0, 0xc1, 0x69, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xe2,
	0xb3, 0xba, 0x9f, 0x6b, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BidiGreetServiceClient is the client API for BidiGreetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BidiGreetServiceClient interface {
	BidiStreamGreet(ctx context.Context, opts ...grpc.CallOption) (BidiGreetService_BidiStreamGreetClient, error)
}

type bidiGreetServiceClient struct {
	cc *grpc.ClientConn
}

func NewBidiGreetServiceClient(cc *grpc.ClientConn) BidiGreetServiceClient {
	return &bidiGreetServiceClient{cc}
}

func (c *bidiGreetServiceClient) BidiStreamGreet(ctx context.Context, opts ...grpc.CallOption) (BidiGreetService_BidiStreamGreetClient, error) {
	stream, err := c.cc.NewStream(ctx, &_BidiGreetService_serviceDesc.Streams[0], "/basic.BidiGreetService/BidiStreamGreet", opts...)
	if err != nil {
		return nil, err
	}
	x := &bidiGreetServiceBidiStreamGreetClient{stream}
	return x, nil
}

type BidiGreetService_BidiStreamGreetClient interface {
	Send(*BidiStreamGreetRequest) error
	Recv() (*BidiGreetStreamResponse, error)
	grpc.ClientStream
}

type bidiGreetServiceBidiStreamGreetClient struct {
	grpc.ClientStream
}

func (x *bidiGreetServiceBidiStreamGreetClient) Send(m *BidiStreamGreetRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *bidiGreetServiceBidiStreamGreetClient) Recv() (*BidiGreetStreamResponse, error) {
	m := new(BidiGreetStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BidiGreetServiceServer is the server API for BidiGreetService service.
type BidiGreetServiceServer interface {
	BidiStreamGreet(BidiGreetService_BidiStreamGreetServer) error
}

func RegisterBidiGreetServiceServer(s *grpc.Server, srv BidiGreetServiceServer) {
	s.RegisterService(&_BidiGreetService_serviceDesc, srv)
}

func _BidiGreetService_BidiStreamGreet_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BidiGreetServiceServer).BidiStreamGreet(&bidiGreetServiceBidiStreamGreetServer{stream})
}

type BidiGreetService_BidiStreamGreetServer interface {
	Send(*BidiGreetStreamResponse) error
	Recv() (*BidiStreamGreetRequest, error)
	grpc.ServerStream
}

type bidiGreetServiceBidiStreamGreetServer struct {
	grpc.ServerStream
}

func (x *bidiGreetServiceBidiStreamGreetServer) Send(m *BidiGreetStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *bidiGreetServiceBidiStreamGreetServer) Recv() (*BidiStreamGreetRequest, error) {
	m := new(BidiStreamGreetRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _BidiGreetService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "basic.BidiGreetService",
	HandlerType: (*BidiGreetServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "BidiStreamGreet",
			Handler:       _BidiGreetService_BidiStreamGreet_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "bidi1/basicpb/basic.proto",
}
