// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Grpc_course/compute_avg/avgpb/avg.proto

package avgpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InputNumber struct {
	Number               int64    `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InputNumber) Reset()         { *m = InputNumber{} }
func (m *InputNumber) String() string { return proto.CompactTextString(m) }
func (*InputNumber) ProtoMessage()    {}
func (*InputNumber) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e0c5af802d2d281, []int{0}
}

func (m *InputNumber) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InputNumber.Unmarshal(m, b)
}
func (m *InputNumber) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InputNumber.Marshal(b, m, deterministic)
}
func (m *InputNumber) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InputNumber.Merge(m, src)
}
func (m *InputNumber) XXX_Size() int {
	return xxx_messageInfo_InputNumber.Size(m)
}
func (m *InputNumber) XXX_DiscardUnknown() {
	xxx_messageInfo_InputNumber.DiscardUnknown(m)
}

var xxx_messageInfo_InputNumber proto.InternalMessageInfo

func (m *InputNumber) GetNumber() int64 {
	if m != nil {
		return m.Number
	}
	return 0
}

type OutputResponse struct {
	Average              float64  `protobuf:"fixed64,1,opt,name=average,proto3" json:"average,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OutputResponse) Reset()         { *m = OutputResponse{} }
func (m *OutputResponse) String() string { return proto.CompactTextString(m) }
func (*OutputResponse) ProtoMessage()    {}
func (*OutputResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e0c5af802d2d281, []int{1}
}

func (m *OutputResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutputResponse.Unmarshal(m, b)
}
func (m *OutputResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutputResponse.Marshal(b, m, deterministic)
}
func (m *OutputResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutputResponse.Merge(m, src)
}
func (m *OutputResponse) XXX_Size() int {
	return xxx_messageInfo_OutputResponse.Size(m)
}
func (m *OutputResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OutputResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OutputResponse proto.InternalMessageInfo

func (m *OutputResponse) GetAverage() float64 {
	if m != nil {
		return m.Average
	}
	return 0
}

func init() {
	proto.RegisterType((*InputNumber)(nil), "avg.InputNumber")
	proto.RegisterType((*OutputResponse)(nil), "avg.OutputResponse")
}

func init() {
	proto.RegisterFile("Grpc_course/compute_avg/avgpb/avg.proto", fileDescriptor_6e0c5af802d2d281)
}

var fileDescriptor_6e0c5af802d2d281 = []byte{
	// 193 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8e, 0xc1, 0x0b, 0x82, 0x30,
	0x14, 0xc6, 0x1b, 0x92, 0xc2, 0x02, 0xa9, 0x05, 0x21, 0x9d, 0x42, 0x88, 0xa4, 0x83, 0x42, 0x1d,
	0x3b, 0x95, 0x87, 0xe8, 0x52, 0x61, 0xb7, 0x2e, 0x32, 0xc7, 0x63, 0x04, 0xea, 0xc6, 0xdc, 0xf6,
	0xf7, 0x87, 0xb3, 0xa0, 0x2e, 0x8f, 0xf7, 0x7d, 0x7c, 0xf0, 0xfb, 0xe1, 0xcd, 0x59, 0x49, 0x56,
	0x32, 0x61, 0x54, 0x07, 0x19, 0x13, 0x8d, 0x34, 0x1a, 0x4a, 0x6a, 0x79, 0x46, 0x2d, 0x97, 0x55,
	0x7f, 0x53, 0xa9, 0x84, 0x16, 0xc4, 0xa3, 0x96, 0xc7, 0x6b, 0x3c, 0xb9, 0xb4, 0xd2, 0xe8, 0xab,
	0x69, 0x2a, 0x50, 0x64, 0x81, 0xfd, 0xd6, 0x7d, 0x11, 0x5a, 0xa1, 0xc4, 0x2b, 0x3e, 0x29, 0xde,
	0xe2, 0xf0, 0x66, 0xb4, 0x34, 0xba, 0x80, 0x4e, 0x8a, 0xb6, 0x03, 0x12, 0xe1, 0x80, 0x5a, 0x50,
	0x94, 0x83, 0x9b, 0xa2, 0xe2, 0x1b, 0x77, 0x77, 0x3c, 0xcb, 0x69, 0xcd, 0x4c, 0x4d, 0xb5, 0x50,
	0x0f, 0x50, 0xf6, 0xc5, 0x80, 0x1c, 0x70, 0x98, 0x0f, 0x2e, 0xc7, 0x61, 0x46, 0xa6, 0x69, 0xaf,
	0xf2, 0x03, 0x5f, 0xce, 0x5d, 0xf3, 0xcf, 0x89, 0x47, 0x09, 0x3a, 0x05, 0xcf, 0xb1, 0x93, 0xaf,
	0x7c, 0x67, 0xbe, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0x28, 0x95, 0x6c, 0xb5, 0xe4, 0x00, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CalculatorServiceClient is the client API for CalculatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CalculatorServiceClient interface {
	ComputeAverage(ctx context.Context, opts ...grpc.CallOption) (CalculatorService_ComputeAverageClient, error)
}

type calculatorServiceClient struct {
	cc *grpc.ClientConn
}

func NewCalculatorServiceClient(cc *grpc.ClientConn) CalculatorServiceClient {
	return &calculatorServiceClient{cc}
}

func (c *calculatorServiceClient) ComputeAverage(ctx context.Context, opts ...grpc.CallOption) (CalculatorService_ComputeAverageClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CalculatorService_serviceDesc.Streams[0], "/avg.CalculatorService/ComputeAverage", opts...)
	if err != nil {
		return nil, err
	}
	x := &calculatorServiceComputeAverageClient{stream}
	return x, nil
}

type CalculatorService_ComputeAverageClient interface {
	Send(*InputNumber) error
	CloseAndRecv() (*OutputResponse, error)
	grpc.ClientStream
}

type calculatorServiceComputeAverageClient struct {
	grpc.ClientStream
}

func (x *calculatorServiceComputeAverageClient) Send(m *InputNumber) error {
	return x.ClientStream.SendMsg(m)
}

func (x *calculatorServiceComputeAverageClient) CloseAndRecv() (*OutputResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(OutputResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CalculatorServiceServer is the server API for CalculatorService service.
type CalculatorServiceServer interface {
	ComputeAverage(CalculatorService_ComputeAverageServer) error
}

func RegisterCalculatorServiceServer(s *grpc.Server, srv CalculatorServiceServer) {
	s.RegisterService(&_CalculatorService_serviceDesc, srv)
}

func _CalculatorService_ComputeAverage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CalculatorServiceServer).ComputeAverage(&calculatorServiceComputeAverageServer{stream})
}

type CalculatorService_ComputeAverageServer interface {
	SendAndClose(*OutputResponse) error
	Recv() (*InputNumber, error)
	grpc.ServerStream
}

type calculatorServiceComputeAverageServer struct {
	grpc.ServerStream
}

func (x *calculatorServiceComputeAverageServer) SendAndClose(m *OutputResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *calculatorServiceComputeAverageServer) Recv() (*InputNumber, error) {
	m := new(InputNumber)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _CalculatorService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "avg.CalculatorService",
	HandlerType: (*CalculatorServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ComputeAverage",
			Handler:       _CalculatorService_ComputeAverage_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "Grpc_course/compute_avg/avgpb/avg.proto",
}
